spring.application.name=myspringbootapp

server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/my_project_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.defer-datasource-initialization=true
# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# JWT
app.jwt.secret=bv1epz19574qdiq7cy0i7hd7a94ghc40812boxqfyput5nvyd0k06vhddjls4j5r # <--- Random
app.jwt.expirationMs=86400000

logging.level.org.springframework.security=TRACE

app.python.interpreter.path=C:/Python312/python.exe
app.python.script.path=C:/Users/TSORa/PycharmProjects/PythonProject/3.1/dorm_assignment.py
app.data.temp.dir=D:/Desktop/test3.1.0/backend/temp_data